eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8888
spring:
  application:
    name: service-zuul
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Duike/SpringcloudConfig/
          searchPaths: respo
          username:
          password:
      label: master